version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    hostname: keycloak
    ports:
      - 8180:8080
    entrypoint: "/keycloak/entrypoint.sh"
    volumes:
      - ./keycloak:/keycloak
  firebase:
    image: borosr/firebase-emulator
    ports:
      - 4141:4141
      - 8200:8200
    environment:
      - PROJECT_ID=iota-vajdasag-brand-b3e95c95
      - FIRESTORE_PORT=8200