version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.2
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8180:8080
    entrypoint: "/keycloak/entrypoint.sh"
    volumes:
      - ./keycloak:/keycloak
