server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:file:./db/demo
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  h2:
    console:
      enabled: true

keycloakBackendClient:
  realm_master: master
  realm2: VajdasagBrand
  client-id: admin-cli
  adminusername: masterAdmin
  adminpassword: 1234567
  user-role: realmadmin

keycloak:
  realm: VajdasagBrand
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: VajdasagClient
  credentials.secret: 68d2287f-17dc-4836-b559-836b9eb971fb
  use-resource-role-mappings: true
  bearer-only: false
