server:
  port: 8081

hu.flowacademy:

spring:
  datasource:
    url: jdbc:h2:file:./testDb/db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

  h2:
    console:
      enabled: true

keycloakBackendClient:
  serverUrl: http://localhost:8180/auth
  realm: VajdasagBrand
  adminusername: initial1
  adminpassword: gsdmnk

keycloak:
  realm: VajdasagBrand
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: VajdasagClient
  credentials.secret: b9d7fc3e-35c7-41b8-a3aa-daa535a271ed
  use-resource-role-mappings: true
  bearer-only: false

