server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:file:./db/demo
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  h2:
    console:
      enabled: true
keycloak:
  realm: VajdasagBrand
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: VajdasagClient
  credentials.secret: 9d709ba1-b04e-4288-a40d-d1b76ee94e15
  use-resource-role-mappings: true
  bearer-only: true
