server:
  port: 8081

hu.flowacademy:

spring:
  datasource:
    url: jdbc:h2:file:./testDb/db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

  h2:
    console:
      enabled: true

keycloakBackendClient:
  serverUrl: http://localhost:8180/auth
  realm: VajdasagBrand
  realm2: VajdasagBrand
  realm_master: master
  adminusername: admin
  adminpassword: admin
  clientpassword: _HLB2!2m8$#ghhk
  client-id: admin-cli
  user-role: realmuser

keycloak:
  realm: VajdasagBrand
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: VajdasagClient
  credentials.secret: 37972d6d-1e0e-45ab-aff8-2d09db1714f5
  use-resource-role-mappings: true
  bearer-only: false


