server:
  port: 8081

hu.flowacademy:

spring:
  datasource:
    url: jdbc:h2:file:./testDb/db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true

  h2:
    console:
      enabled: true

keycloakBackendClient:
  serverUrl: http://localhost:8180/auth
  realm: VajdasagBrand
  adminusername: admin
  adminpassword: admin

keycloak:
  realm: VajdasagBrand
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: VajdasagClient
  credentials.secret: 9d709ba1-b04e-4288-a40d-d1b76ee94e15
  use-resource-role-mappings: true
  bearer-only: false

