# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for all branches
  push:
    branches: 
      - '**'
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Test frontend
        run: npm test -- --coverage

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: frontend/coverage/lcov-report

      - name: Build frontend
        run: npm run build

      - name: Archive frontend bundle
        uses: actions/upload-artifact@v2
        with:
          name: iota-vajdasag-brand-frontend
          path: frontend/build
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run maven test
        run: mvn -B clean test

  deploy_staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [build_frontend, build-backend]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: iota-vajdasag-brand-frontend
          path: frontend/build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IOTA_VAJDASAG_BRAND_B3E95C95 }}'
          projectId: iota-vajdasag-brand-b3e95c95
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
