name: Spring

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-backend:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # TODO start keycloak
      - name: Run maven test
        run: mvn -B clean test
